apiVersion: apps/v1
kind: Deployment
metadata:
  name: netology-ml
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: netology-ml
  template:
    metadata:
      labels:
        app: netology-ml
    spec:
      containers:
        - name: tomcat
          image: tomcat:8.5.69
          ports:
            - containerPort: 8080
